# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

echo "Welcome In My Notes"
echo "Git Shorthand"
echo "[ga:git add] [gaa:git add .] [gs:git status]"
echo "[gb:git branch] [gck:git checkout] [gc:git commit -m {message} ] [gp:git push]"
echo "[graph: git log decoration]"
echo "[git reset auth] git config --global credential.helper wincred"

echo ""
echo "Utilities"
echo "live-server, node-sass"

echo ""
echo "Esp flash micropython"
echo "esptool.py --port com5 erase_flash"
echo "esptool.py --chip esp32 --port com5 write_flash -z 0x1000 [name file bin flash]"

